name: Shared Artifacts Workflow

on: [push]

jobs:
  upload-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create a log file
        run: echo "This is a log message from upload-artifact job" > log.txt

      - name: Upload log artifact
        uses: actions/upload-artifact@v4
        with:
          name: log-file
          path: log.txt

  download-artifact:
    runs-on: ubuntu-latest
    needs: upload-artifact  # Ensure job2 runs after upload-artifact job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download log artifact
        uses: actions/download-artifact@v4
        with:
          name: log-file
          path: ./downloaded_artifacts

      - name: Display the log file content
        run: cat ./downloaded_artifacts/log.txt

  cleanup-artifacts:
    runs-on: ubuntu-latest
    needs: download-artifact  # Ensure cleanup runs after download-artifact job

    steps:
    - uses: geekyeggo/delete-artifact@v5
      with:
          name: |
              artifact-*
              binary-file
              output
